### ISSUE TITLE
This shall be updated before final publishing

### ISSUE THREAD

**Issue by SchrodingerZhu** [outloudvi/polya-server#1]
https://github.com/outloudvi/polya-server/blob/6ff8d0890e60321a981d8184e15411bd5f08956f/client_config.json#L1

A new version will be given later. I am busy preparing lectures now.

**Comment by SchrodingerZhu** [comment]
see https://github.com/project-polya/tulip/blob/master/global.md

**Comment by outloudvi** [comment]
fixed by 342431d.
